### ISSUE TITLE
TODO/FIXME Count 10

### ISSUE THREAD

**Issue by mattcollier** [digitalbazaar/jsonld-signatures#102]
- [ ] FIXME: forge supports alternative alphabets now -- use that instead?
       Commit: (3cbcc73) Update test suite and fix related bugs.
       File:  [lib/util.js:214](https://github.com/digitalbazaar/jsonld-signatures/blob/master/lib/util.js#L214)
       Dave Longley commented a year ago

  - [ ] FIXME: forge supports alternative alphabets now -- use that instead?
       Commit: (363eade) Reorganize suites and rework APIs and internals.
       File:  [lib/util.js:191](https://github.com/digitalbazaar/jsonld-signatures/blob/master/lib/util.js#L191)
       Dave Longley commented a year ago

  - [ ] TODO: only require dynamically as needed or according to build
       Commit: (74e1a97) Move suites and utilities to a separate module.
       File:  [lib/suites.js:9](https://github.com/digitalbazaar/jsonld-signatures/blob/master/lib/suites.js#L9)
       Dave Longley commented a year ago

  - [ ] TODO: only require dynamically as needed or according to build
       Commit: (2a16a2d) Add CustomSuite test and reorganize exposed suites/purposes.
       File:  [lib/purposes.js:9](https://github.com/digitalbazaar/jsonld-signatures/blob/master/lib/purposes.js#L9)
       Dave Longley commented a year ago

  - [ ] TODO: support `ProofChain`
       Commit: (363eade) Reorganize suites and rework APIs and internals.
       File:  [lib/jsonld-signatures.js:14](https://github.com/digitalbazaar/jsonld-signatures/blob/master/lib/jsonld-signatures.js#L14)
       Dave Longley commented a year ago

  - [ ] TODO: consider in-place editing to optimize
       Commit: (7ca93f8) Compact input to security context for consistency.
       File:  [lib/ProofSet.js:301](https://github.com/digitalbazaar/jsonld-signatures/blob/master/lib/ProofSet.js#L301)
       Dave Longley commented a year ago

  - [ ] TODO: consider in-place editing to optimize when `compactProof`
       Commit: (fb60a05) Reimplement `proofTermDefined` as `compactProof`.
       File:  [lib/ProofSet.js:240](https://github.com/digitalbazaar/jsonld-signatures/blob/master/lib/ProofSet.js#L240)
       Dave Longley commented a year ago

  - [ ] TODO: optimize to modify document in place to maximize optimization
       Commit: (7ca93f8) Compact input to security context for consistency.
       File:  [lib/ProofSet.js:96](https://github.com/digitalbazaar/jsonld-signatures/blob/master/lib/ProofSet.js#L96)
       Dave Longley commented a year ago

  - [ ] TODO: implement
       Commit: (363eade) Reorganize suites and rework APIs and internals.
       File:  [lib/ProofChain.js:7](https://github.com/digitalbazaar/jsonld-signatures/blob/master/lib/ProofChain.js#L7)
       Dave Longley commented a year ago

  - [ ] FIXME: hack to ensure delay is set first
       Commit: (c3e9059) use webpack and karma.
       File:  [tests/test-karma.js:15](https://github.com/digitalbazaar/jsonld-signatures/blob/master/tests/test-karma.js#L15)
       David I. Lehn commented 3 years ago

**Comment by aljones15** [comment]
I made an issue for implementing `ProofChain` here: https://github.com/digitalbazaar/jsonld-signatures/issues/110
